# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI)
#

vdrm-y := vdrm_drv.o \
	  vdrm_connector.o \
	  vdrm_plane.o \
	  vdrm_crtc.o \
	  vdrm_controller.o

obj-y	+= vdrm.o
